

spring:
#    data:
#      mongodb:
#        database: report
#        host: blog.sakuramk.cn
#        port: 27917
#        model: com.report.bean
#        print: true
#
#      jackson:
#        time-zone: Asia/Shanghai
    profiles:
      active: pro


server:
  port: 8081

